#input_dir: 'contextual_dataset'
input_dir: '/home/alexander/SUNRGBD/dataset/contextual/combined_full_size'
mode: 'train'
output_dir: 'delete_model'
seed: ~
checkpoint: 'delete_model'
max_steps: ~
max_epochs: 200
summary_freq: 100
progress_freq: 50
trace_freq: 0
display_freq: 0
save_freq: 2000
separable_conv: False
aspect_ratio: 1.0
lab_colorization: False
batch_size: 10
which_direction: BtoA
ngf: 64
ndf: 64
scale_size: 400
flip: True
lr: 0.0002
beta1: 0.5
l1_weight: 100.0
gan_weight: 1.0
output_filetype: 'png'
count_parameters: False
summarize_histograms: False
provide_context: False
